[build]
  command = "npm run build:static"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Tell Netlify to ignore Next.js
[build.processing.html]
  pretty_urls = true
