[build]
  command = "npm run build:static"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
