[build]
  command = "node scripts/netlify-build.js"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  ROLLUP_WASM_NODE = "true"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
